# Generated by Django 5.0.1 on 2024-01-30 21:28

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('chest_number', models.IntegerField(null=True)),
                ('gender', models.CharField(choices=[('m', 'Male'), ('f', 'Female')], default='f', max_length=3)),
                ('department', models.CharField(choices=[('CS', 'CS'), ('CL', 'CL'), ('BT', 'BT'), ('EC', 'EC'), ('ME', 'Mech'), ('MA', 'Auto'), ('MP', 'MP')], default='cs', max_length=5)),
                ('year', models.IntegerField(default=0)),
                ('solo_event_registered_count', models.IntegerField(default=0)),
                ('group_event_registered_count', models.IntegerField(default=0)),
            ],
        ),
    ]
