# Generated by Django 5.0.1 on 2024-02-07 00:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_alter_profile_department'),
        ('artsapi', '0007_remove_team_program_team_program'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='registered_events',
            field=models.ManyToManyField(blank=True, to='artsapi.program'),
        ),
    ]
