# Generated by Django 5.0.1 on 2024-01-30 21:28

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='DepartmentPoints',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('department', models.CharField(choices=[('CS', 'CS'), ('CL', 'CL'), ('BT', 'BT'), ('EC', 'EC'), ('ME', 'Mech'), ('MA', 'Auto'), ('MP', 'MP')], default='CS', max_length=5)),
                ('group_event_score', models.IntegerField(default=0)),
                ('solo_event_score', models.IntegerField(default=0)),
                ('overall_score', models.IntegerField(default=1)),
            ],
        ),
        migrations.CreateModel(
            name='Program',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('slot_time', models.DateTimeField(default=django.utils.timezone.now)),
                ('program_gender_type', models.CharField(choices=[('m', 'Male'), ('f', 'Female')], default='m', max_length=7)),
                ('program_type', models.CharField(choices=[('g', 'Group'), ('s', 'Solo')], default='g', max_length=5)),
                ('program_comes_under', models.CharField(choices=[('music', 'Music'), ('instruments', 'Instruments'), ('dance', 'Dance'), ('theatre', 'Theatre Events'), ('finearts', 'Fine Arts')], default='music', max_length=80)),
                ('registered_users', models.ManyToManyField(blank=True, related_name='registered_user', to='accounts.profile')),
                ('winners', models.ManyToManyField(blank=True, related_name='won_programs', to='accounts.profile')),
                ('winners_position', models.ManyToManyField(blank=True, related_name='winner_ranking', to='accounts.profile')),
            ],
        ),
    ]
