# Generated by Django 5.0.1 on 2024-02-06 02:44

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('artsapi', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='program',
            name='max_member_limit',
            field=models.IntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='departmentpoints',
            name='department',
            field=models.CharField(choices=[('CS', 'CS'), ('AM', 'CL'), ('BT', 'BT'), ('ECA', 'ECA'), ('ECB', 'ECB'), ('MEA', 'Mech A'), ('MEB', 'Mech B'), ('MA', 'Auto'), ('MP', 'MP')], default='CS', max_length=5),
        ),
        migrations.AlterField(
            model_name='program',
            name='program_gender_type',
            field=models.CharField(choices=[('m', 'Male'), ('f', 'Female'), ('a', 'All')], default='m', max_length=7),
        ),
        migrations.CreateModel(
            name='Team',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('members', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='members', to=settings.AUTH_USER_MODEL)),
                ('program', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='artsapi.program')),
                ('team_lead', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='team_lead', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
