# Generated by Django 5.0.1 on 2024-02-06 22:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('artsapi', '0003_alter_departmentpoints_department'),
    ]

    operations = [
        migrations.AddField(
            model_name='team',
            name='share_link',
            field=models.SlugField(default=0),
        ),
    ]
