# Generated by Django 5.0.1 on 2024-02-07 00:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('artsapi', '0005_remove_team_members_team_members'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='team',
            name='program',
        ),
        migrations.AddField(
            model_name='team',
            name='program',
            field=models.ManyToManyField(to='artsapi.program'),
        ),
    ]
