# Generated by Django 5.0.1 on 2024-02-07 00:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('artsapi', '0006_remove_team_program_team_program'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='team',
            name='program',
        ),
        migrations.AddField(
            model_name='team',
            name='program',
            field=models.ForeignKey(default=2, on_delete=django.db.models.deletion.CASCADE, related_name='program_team', to='artsapi.program'),
            preserve_default=False,
        ),
    ]
