# Generated by Django 5.0.1 on 2024-02-16 06:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_alter_profile_registered_events'),
        ('artsapi', '0007_remove_team_program_team_program'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='program',
            name='winners',
        ),
        migrations.RemoveField(
            model_name='program',
            name='winners_position',
        ),
        migrations.AddField(
            model_name='program',
            name='winner_first',
            field=models.ManyToManyField(blank=True, related_name='first', to='accounts.profile'),
        ),
        migrations.AddField(
            model_name='program',
            name='winner_second',
            field=models.ManyToManyField(blank=True, related_name='second', to='accounts.profile'),
        ),
        migrations.AddField(
            model_name='program',
            name='winner_third',
            field=models.ManyToManyField(blank=True, related_name='third', to='accounts.profile'),
        ),
    ]
